import { useState, useMemo } from 'react'
import { T } from '../data/theme'
import { Masthead, Eyebrow, Rule, SourceLine, Screen } from '../components/shared'
import { useCycle, detectSymptomPatterns } from '../hooks/useCycle'
import useLuna from '../store/useLuna'
import { buildCheatsheet, cheatsheetText } from '../lib/cheatsheet'

export default function Cheatsheet() {
  const store = useLuna()
  const { back, logs, displayName } = store
  const cycle = useCycle(store)
  const patterns = useMemo(
    () => detectSymptomPatterns(logs, cycle.periodHistory, cycle.cycleLength, cycle.periodLength),
    [logs, cycle.periodHistory, cycle.cycleLength, cycle.periodLength]
  )
  const points = useMemo(
    () => buildCheatsheet({ logs, cycle, patterns }),
    [logs, cycle, patterns]
  )
  const [copied, setCopied] = useState(false)

  const copyAll = async () => {
    const text = cheatsheetText(points, { displayName })
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 1800)
    } catch {
      // Fallback for browsers without async clipboard — open a window
      // with the text so the user can select-all and copy manually.
      const w = window.open('', '_blank')
      if (w) {
        w.document.write(`<pre style="font-family:Georgia,serif;padding:24px;white-space:pre-wrap;">${text.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]))}</pre>`)
        w.document.close()
      }
    }
  }

  const printPage = () => {
    const today = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
    const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]))
    const html = `<!DOCTYPE html><html><head><title>Notes for your appointment</title>
<style>
  body{font-family:Georgia,serif;padding:40px;max-width:640px;margin:0 auto;color:#1a1310;line-height:1.55;}
  h1{font-size:24px;margin-bottom:4px;font-weight:500;letter-spacing:-0.4px;}
  .sub{font-size:12px;color:#888;margin-bottom:28px;}
  .item{margin:18px 0;padding:14px 16px;border:1px solid #e8e3d8;border-radius:6px;}
  .title{font-size:15px;font-weight:600;margin-bottom:10px;}
  .label{font-size:10px;letter-spacing:1.5px;text-transform:uppercase;color:#888;margin-top:6px;}
  .body{font-size:14px;color:#333;margin-top:2px;}
  .footer{margin-top:32px;padding-top:14px;border-top:1px solid #e8e3d8;font-size:11px;color:#999;font-style:italic;}
</style></head><body>
<h1>Notes for our appointment</h1>
<div class="sub">${displayName ? esc(displayName) + ' &middot; ' : ''}${esc(today)}</div>
${points.map((p, i) => `
  <div class="item">
    <div class="title">${i + 1}. ${esc(p.title)}</div>
    <div class="label">Say</div>
    <div class="body">${esc(p.say)}</div>
    <div class="label">Why it matters</div>
    <div class="body">${esc(p.why)}</div>
    <div class="label">Source</div>
    <div class="body">${esc(p.source)}</div>
  </div>
`).join('')}
<div class="footer">Generated by Luna. Not a diagnosis — wording for the conversation.</div>
</body></html>`
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(html)
    w.document.close()
    w.print()
  }

  return (
    <Screen padBottom={40}>
      <div style={{ padding: '12px 22px 0', color: T.text }}>
        <Masthead issue="For your next visit" onBack={back} />
        <Eyebrow>Wording, ready to take with you</Eyebrow>
        <div style={{ fontFamily: T.serif, fontSize: 30, fontWeight: 500, letterSpacing: -0.7, lineHeight: 1.08 }}>
          What's worth bringing up.
        </div>
        <div style={{ fontFamily: T.serif, fontSize: 14.5, lineHeight: 1.6, color: T.muted, marginTop: 10 }}>
          Luna read your cycles and pulled together the conversation. Use it as a script, edit it, or just bring the page in. The point is that you don't have to find the words in the room.
        </div>
        <Rule />

        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {points.map((p, i) => (
            <div key={p.id} className="glass-card" style={{ padding: 16, borderLeft: `3px solid ${T.accent}`, borderRadius: T.r }}>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 10 }}>
                <div style={{ fontFamily: T.mono, fontSize: 11, color: T.accent, fontWeight: 700, letterSpacing: 1 }}>
                  {String(i + 1).padStart(2, '0')}
                </div>
                <div style={{ fontFamily: T.serif, fontSize: 17, fontWeight: 500, lineHeight: 1.3, letterSpacing: -0.1 }}>
                  {p.title}
                </div>
              </div>
              <div style={{ marginBottom: 10 }}>
                <div style={{ fontFamily: T.mono, fontSize: 9.5, letterSpacing: 1.4, fontWeight: 600, color: T.muted, marginBottom: 4 }}>
                  Say
                </div>
                <div style={{ fontFamily: T.serif, fontSize: 14.5, lineHeight: 1.55, color: T.text, fontStyle: 'italic' }}>
                  "{p.say}"
                </div>
              </div>
              <div style={{ marginBottom: 10 }}>
                <div style={{ fontFamily: T.mono, fontSize: 9.5, letterSpacing: 1.4, fontWeight: 600, color: T.muted, marginBottom: 4 }}>
                  Why it matters
                </div>
                <div style={{ fontFamily: T.sans, fontSize: 12.5, lineHeight: 1.55, color: T.text }}>
                  {p.why}
                </div>
              </div>
              <div style={{ fontFamily: T.mono, fontSize: 9.5, letterSpacing: 0.5, color: T.muted, paddingTop: 8, borderTop: `1px solid ${T.hair}` }}>
                SOURCE — {p.source}
              </div>
            </div>
          ))}
        </div>

        <div style={{ marginTop: 22, display: 'flex', gap: 10 }}>
          <button onClick={copyAll}
            style={{ flex: 1, background: T.accent, color: '#fff', border: 'none', padding: '12px 14px', cursor: 'pointer', fontFamily: T.sans, fontSize: 12, fontWeight: 600, letterSpacing: 0.4, borderRadius: T.r }}>
            {copied ? 'Copied' : 'Copy to clipboard'}
          </button>
          <button onClick={printPage}
            style={{ flex: 1, background: 'transparent', color: T.text, border: `1px solid ${T.text}`, padding: '12px 14px', cursor: 'pointer', fontFamily: T.sans, fontSize: 12, fontWeight: 600, letterSpacing: 0.4, borderRadius: T.r }}>
            Print page
          </button>
        </div>

        <SourceLine>Generated from your logs · not a diagnosis · meant for the conversation</SourceLine>
        <div style={{ height: 16 }} />
      </div>
    </Screen>
  )
}
