import { useState } from 'react'
import { T } from '../data/theme'
import { Masthead, Eyebrow, Rule, SourceLine, Screen, Icons } from '../components/shared'
import { RED_FLAGS, ARTICLES } from '../data/lunaData'
import { PhaseFlourish } from '../components/phaseFlourishes'
import { useCycle } from '../hooks/useCycle'
import useLuna from '../store/useLuna'

// Defensive escape for anything interpolated into the PDF HTML template.
// No user-supplied content reaches here today, but if RED_FLAGS or any
// other source ever does, this prevents script injection in the print
// window that exportPDF opens.
function htmlEscape(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

export default function HealthWatch() {
  const store = useLuna()
  const { back, goArticle } = store
  const cycle = useCycle(store)
  const phase = cycle?.phase
  const acc = phase?.color || T.accent
  const [answers, setAnswers] = useState({})
  const toggle = (id) => setAnswers((a) => ({ ...a, [id]: !a[id] }))
  const triggered = RED_FLAGS.filter((f) => answers[f.id])

  const exportPDF = () => {
    const flagged = RED_FLAGS.filter((f) => answers[f.id])
    const generated = new Date().toLocaleDateString('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'})
    const html = `<!DOCTYPE html><html><head><title>Luna Health Summary</title>
<style>
  body{font-family:Georgia,serif;padding:40px;max-width:600px;margin:0 auto;color:#1a1310;}
  h1{font-size:26px;margin-bottom:4px;}
  .sub{font-size:13px;color:#888;margin-bottom:32px;}
  h2{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#888;margin:28px 0 10px;}
  .item{margin:10px 0;padding:12px 14px;border:1px solid #e8e3d8;border-radius:4px;}
  .q{font-size:15px;font-weight:600;margin-bottom:4px;}
  .a{font-size:13px;color:#555;}
  .none{font-size:14px;color:#888;font-style:italic;}
  .footer{margin-top:36px;padding-top:16px;border-top:1px solid #e8e3d8;font-size:11px;color:#999;line-height:1.5;}
</style></head><body>
<h1>Luna Health Screener Summary</h1>
<div class="sub">Generated ${htmlEscape(generated)}</div>
<h2>Flagged items (${flagged.length})</h2>
${flagged.length === 0
  ? '<div class="none">No items flagged.</div>'
  : flagged.map((f) => `<div class="item"><div class="q">${htmlEscape(f.q)}</div><div class="a">${htmlEscape(f.a)}</div></div>`).join('')
}
<h2>All items reviewed</h2>
${RED_FLAGS.map((f) => `<div class="item" style="opacity:${answers[f.id]?1:.45}"><div class="q">${answers[f.id]?'✓ ':''} ${htmlEscape(f.q)}</div></div>`).join('')}
<div class="footer">This summary was generated by Luna for discussion with a healthcare provider.<br/>It is not a diagnosis. Luna — cycle tracking &amp; health education.</div>
</body></html>`
    const w = window.open('', '_blank')
    w.document.write(html)
    w.document.close()
    w.print()
  }

  return (
    <Screen padBottom={30}>
      <div style={{ padding: '12px 22px 0', color: T.text }}>
        <Masthead issue="When something feels off" onBack={back} />
        <div className="insight-stagger" style={{ animationDelay: '0ms' }}>
          <Eyebrow color={acc}>Not a diagnosis — words to take to your doctor</Eyebrow>
        </div>
        <div className="insight-stagger" style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, animationDelay: '40ms' }}>
          <div style={{ fontFamily: T.serif, fontSize: 28, fontWeight: 500, letterSpacing: -0.6, lineHeight: 1.1, flex: 1 }}>
            What you've been feeling is real.
          </div>
          {phase && (
            <div aria-hidden="true" style={{ color: acc, opacity: 0.55, paddingTop: 2 }}>
              <PhaseFlourish phaseId={phase.id} size={22} />
            </div>
          )}
        </div>
        <div className="insight-stagger" style={{ fontFamily: T.serif, fontSize: 14.5, lineHeight: 1.6, color: T.muted, marginTop: 10, fontStyle: 'italic', animationDelay: '90ms' }}>
          Tap anything that's been showing up for you lately. Luna will gather the language so the next conversation with your provider is easier.
        </div>
        <Rule />

        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {RED_FLAGS.map((f, i) => {
            const on = !!answers[f.id]
            return (
              <button key={f.id} onClick={() => toggle(f.id)}
                className="insight-stagger alive-card frost-card"
                style={{
                  border: `1px solid ${on ? acc + '55' : 'rgba(26,19,16,0.06)'}`,
                  background: on ? acc + '14' : 'rgba(253,250,245,0.55)',
                  padding: '16px 16px 16px 48px',
                  cursor: 'pointer', fontFamily: 'inherit', color: T.text, textAlign: 'left',
                  position: 'relative', borderRadius: 18,
                  boxShadow: on ? `0 14px 30px -22px ${acc}60` : '0 10px 22px -22px rgba(26,19,16,0.18)',
                  animationDelay: `${140 + i * 40}ms`,
                  transition: 'all 0.2s var(--ease-out)',
                }}>
                <div style={{
                  position: 'absolute', top: 16, left: 16, width: 22, height: 22,
                  border: `1.5px solid ${on ? acc : 'rgba(26,19,16,0.22)'}`,
                  background: on ? acc : 'rgba(253,250,245,0.6)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  color: '#fff', borderRadius: 8,
                  boxShadow: on ? `0 6px 12px -6px ${acc}80` : 'none',
                  transition: 'all 0.2s var(--ease-out)',
                }}>
                  {on && Icons.check}
                </div>
                <div style={{ fontFamily: T.serif, fontSize: 15, fontWeight: 500, marginBottom: on ? 6 : 0, lineHeight: 1.4, letterSpacing: -0.1 }}>{f.q}</div>
                {on && <div style={{ fontFamily: T.serif, fontStyle: 'italic', fontSize: 13, color: T.muted, lineHeight: 1.55, animation: 'fadeUp .2s ease-out both' }}>{f.a}</div>}
              </button>
            )
          })}
        </div>

        {triggered.length > 0 && (
          <div className="frost-card alive-card" style={{ marginTop: 22, padding: 20, background: T.text, color: '#FAF4ED', borderRadius: 22, boxShadow: `0 16px 36px -20px rgba(26,19,16,0.5)`, animation: 'fadeUp .25s ease-out both' }}>
            <div style={{ fontFamily: T.serif, fontStyle: 'italic', fontSize: 13, color: acc, fontWeight: 500, marginBottom: 10, letterSpacing: -0.1 }}>worth bringing up</div>
            <div style={{ fontFamily: T.serif, fontSize: 19, lineHeight: 1.4, marginBottom: 10, fontStyle: 'italic', letterSpacing: -0.3 }}>
              {triggered.length === 1 ? 'One thing' : `${triggered.length} of these`} is worth a conversation with your provider.
            </div>
            <div style={{ fontFamily: T.serif, fontSize: 13.5, color: 'rgba(250,244,237,0.72)', lineHeight: 1.6, marginBottom: 16, fontStyle: 'italic' }}>
              Luna will make a one-page summary you can email or print, so you don't have to find the words in the room.
            </div>
            <button onClick={exportPDF} className="alive-card" style={{ background: acc, color: '#fff', border: 'none', padding: '11px 18px', cursor: 'pointer', fontFamily: T.sans, fontSize: 11.5, letterSpacing: 0.3, fontWeight: 600, borderRadius: 999, boxShadow: `0 10px 22px -10px ${acc}80` }}>
              Make me a summary →
            </button>
          </div>
        )}

        <Rule />
        <Eyebrow color={acc}>To read with a cup of tea</Eyebrow>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {['pmdd','endo','iron','pcos'].map((id) => {
            const a = ARTICLES.find((x) => x.id === id)
            if (!a) return null
            return (
              <button key={id} onClick={() => goArticle(id)}
                className="alive-card frost-card"
                style={{ background: 'rgba(253,250,245,0.55)', border: '1px solid rgba(26,19,16,0.06)', textAlign: 'left', padding: 16, cursor: 'pointer', color: T.text, fontFamily: 'inherit', borderRadius: 18, boxShadow: `0 14px 30px -22px ${acc}40` }}>
                <div style={{ fontFamily: T.serif, fontSize: 16, fontWeight: 500, lineHeight: 1.3, letterSpacing: -0.1 }}>{a.title} →</div>
                <div style={{ fontFamily: T.serif, fontStyle: 'italic', fontSize: 12, color: T.muted, marginTop: 4 }}>{a.read} · {a.cat}</div>
              </button>
            )
          })}
        </div>
        <SourceLine>This screener is informational. It does not replace a clinical evaluation.</SourceLine>
        <div style={{ height: 16 }} />
      </div>
    </Screen>
  )
}
