import { useState } from 'react'
import { T } from '../data/theme'
import { Masthead, Eyebrow, Rule, SourceLine, Screen, Icons } from '../components/shared'
import { RED_FLAGS, ARTICLES } from '../data/lunaData'
import useLuna from '../store/useLuna'

// Defensive escape for anything interpolated into the PDF HTML template.
// No user-supplied content reaches here today, but if RED_FLAGS or any
// other source ever does, this prevents script injection in the print
// window that exportPDF opens.
function htmlEscape(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

export default function HealthWatch() {
  const { back, goArticle } = useLuna()
  const [answers, setAnswers] = useState({})
  const toggle = (id) => setAnswers((a) => ({ ...a, [id]: !a[id] }))
  const triggered = RED_FLAGS.filter((f) => answers[f.id])

  const exportPDF = () => {
    const flagged = RED_FLAGS.filter((f) => answers[f.id])
    const generated = new Date().toLocaleDateString('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'})
    const html = `<!DOCTYPE html><html><head><title>Luna Health Summary</title>
<style>
  body{font-family:Georgia,serif;padding:40px;max-width:600px;margin:0 auto;color:#1a1310;}
  h1{font-size:26px;margin-bottom:4px;}
  .sub{font-size:13px;color:#888;margin-bottom:32px;}
  h2{font-size:11px;letter-spacing:2px;text-transform:uppercase;color:#888;margin:28px 0 10px;}
  .item{margin:10px 0;padding:12px 14px;border:1px solid #e8e3d8;border-radius:4px;}
  .q{font-size:15px;font-weight:600;margin-bottom:4px;}
  .a{font-size:13px;color:#555;}
  .none{font-size:14px;color:#888;font-style:italic;}
  .footer{margin-top:36px;padding-top:16px;border-top:1px solid #e8e3d8;font-size:11px;color:#999;line-height:1.5;}
</style></head><body>
<h1>Luna Health Screener Summary</h1>
<div class="sub">Generated ${htmlEscape(generated)}</div>
<h2>Flagged items (${flagged.length})</h2>
${flagged.length === 0
  ? '<div class="none">No items flagged.</div>'
  : flagged.map((f) => `<div class="item"><div class="q">${htmlEscape(f.q)}</div><div class="a">${htmlEscape(f.a)}</div></div>`).join('')
}
<h2>All items reviewed</h2>
${RED_FLAGS.map((f) => `<div class="item" style="opacity:${answers[f.id]?1:.45}"><div class="q">${answers[f.id]?'✓ ':''} ${htmlEscape(f.q)}</div></div>`).join('')}
<div class="footer">This summary was generated by Luna for discussion with a healthcare provider.<br/>It is not a diagnosis. Luna — cycle tracking &amp; health education.</div>
</body></html>`
    const w = window.open('', '_blank')
    w.document.write(html)
    w.document.close()
    w.print()
  }

  return (
    <Screen padBottom={30}>
      <div style={{ padding: '12px 22px 0', color: T.text }}>
        <Masthead issue="Health Watch" onBack={back} />
        <Eyebrow>SCREENER · NOT A DIAGNOSIS</Eyebrow>
        <div style={{ fontFamily: T.serif, fontSize: 28, fontWeight: 500, letterSpacing: -0.6, lineHeight: 1.1 }}>When should you talk to a doctor?</div>
        <div style={{ fontFamily: T.serif, fontSize: 14.5, lineHeight: 1.55, color: T.muted, marginTop: 10 }}>
          Tap any that apply. Not a diagnosis — a conversation starter for your provider.
        </div>
        <Rule />

        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {RED_FLAGS.map((f) => {
            const on = !!answers[f.id]
            return (
              <button key={f.id} onClick={() => toggle(f.id)}
                style={{ border: `1px solid ${on ? T.accent : T.hair}`, background: on ? T.accent + '0E' : T.card, padding: '14px 14px 14px 44px', cursor: 'pointer', fontFamily: 'inherit', color: T.text, textAlign: 'left', position: 'relative', borderRadius: T.r }}>
                <div style={{ position: 'absolute', top: 14, left: 14, width: 18, height: 18, border: `1.5px solid ${on ? T.accent : T.muted}`, background: on ? T.accent : 'transparent', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', borderRadius: 2 }}>
                  {on && Icons.check}
                </div>
                <div style={{ fontFamily: T.serif, fontSize: 14.5, fontWeight: 500, marginBottom: on ? 6 : 0, lineHeight: 1.35 }}>{f.q}</div>
                {on && <div style={{ fontFamily: T.sans, fontSize: 12, color: T.muted, lineHeight: 1.45, animation: 'fadeUp .2s ease-out both' }}>{f.a}</div>}
              </button>
            )
          })}
        </div>

        {triggered.length > 0 && (
          <div style={{ marginTop: 22, padding: 18, background: T.text, color: '#FAF4ED', borderRadius: T.r, animation: 'fadeUp .25s ease-out both' }}>
            <div style={{ fontFamily: T.sans, fontSize: 10, letterSpacing: 2, color: T.accent, fontWeight: 700, marginBottom: 8 }}>NEXT STEP</div>
            <div style={{ fontFamily: T.serif, fontSize: 18, lineHeight: 1.3, marginBottom: 10 }}>
              You flagged <strong>{triggered.length}</strong> {triggered.length === 1 ? 'item' : 'items'}. <em style={{ color: T.accent }}>Worth a doctor's visit.</em>
            </div>
            <div style={{ fontFamily: T.sans, fontSize: 12, color: 'rgba(250,244,237,0.7)', lineHeight: 1.5, marginBottom: 14 }}>
              Export this as a PDF you can email to your provider.
            </div>
            <button onClick={exportPDF} style={{ background: T.accent, color: '#fff', border: 'none', padding: '10px 14px', cursor: 'pointer', fontFamily: T.sans, fontSize: 11, letterSpacing: 2, fontWeight: 700, borderRadius: T.r }}>
              EXPORT DOCTOR-READY PDF →
            </button>
          </div>
        )}

        <Rule />
        <Eyebrow>LEARN MORE</Eyebrow>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {['pmdd','endo','iron','pcos'].map((id) => {
            const a = ARTICLES.find((x) => x.id === id)
            if (!a) return null
            return (
              <button key={id} onClick={() => goArticle(id)}
                style={{ background: 'transparent', border: 'none', textAlign: 'left', padding: 0, cursor: 'pointer', color: T.text, fontFamily: 'inherit' }}>
                <div style={{ fontFamily: T.serif, fontSize: 16, fontWeight: 500, lineHeight: 1.25 }}>{a.title} →</div>
                <div style={{ fontFamily: T.sans, fontSize: 11.5, color: T.muted, marginTop: 2 }}>{a.read} · {a.cat}</div>
              </button>
            )
          })}
        </div>
        <SourceLine>This screener is informational. It does not replace a clinical evaluation.</SourceLine>
        <div style={{ height: 16 }} />
      </div>
    </Screen>
  )
}
